# Generated by Django 6.1.2 on 2026-10-07 12:15

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question_explanation_question_source_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquestion',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='manual_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('FILE_UPLOAD', 'File Upload')], default='MCQ', max_length=20),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='is_graded',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('FILE_UPLOAD', 'File Upload')], default='MCQ', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default='', help_text='For MCQ: answer explanation. For File Upload: grading instructions shown to the admin reviewer.'),
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=core.models.submission_file_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_files', to='core.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_files', to='core.question')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
